RentalWebsite/Controllers/SurfboardsController.cs
using System.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvc_surfboard.Data;
using mvc_surfboard.Models;

namespace mvc_surfboard.Controllers
{
    public class SurfboardsController : Controller
    {
        private readonly mvc_surfboardContext _context;
        private readonly HttpClient _httpClient;
        private readonly WebApiService _apiService;

        public SurfboardsController(mvc_surfboardContext context, HttpClient httpClient, WebApiService apiService)
        {
            _context = context;
            _httpClient = httpClient;
            _apiService = apiService;
        }

        #region Index
        // GET: Surfboards
        public async Task<IActionResult> Index()
        {
            if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                var surfboards = await _apiService.GetSurfboardsAsync("2.0");
                return View(surfboards);
            }
            else
            {
                var surfboards = await _apiService.GetSurfboardsAsync("1.0");
                return View(surfboards);
            }
        }
        #endregion

        #region List
        // GET: Surfboards
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> List(
            string sortOrder,
            string searchString,
            string currentFilter,
            int? pageNumber
            )
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            // ViewData["LengthSortParm"] = sortOrder == "Length" ? "length_desc" : "Length";
            ViewData["LengthSortParm"] = String.IsNullOrEmpty(sortOrder) ? "length_desc" : "";
            ViewData["TypeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "type_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var boards = from b in _context.Surfboard
                         select b;

            switch (sortOrder)
            {
                case "name_desc":
                    boards = boards.OrderByDescending(s => s.Name);
                    break;
                case "length_desc":
                    boards = boards.OrderBy(s => s.Length);
                    break;
                case "type_desc":
                    boards = boards.OrderByDescending(s => s.Type);
                    break;
                default:
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedList<Surfboard>.CreateAsync(boards.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        #endregion

        #region Create
        [Authorize(Roles = "Admin")]
        // GET: Surfboards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Surfboards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Length,Width,Thickness,Volume,Type,Price,Equipment,ImgUrl,RowVersion")] Surfboard surfboard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(surfboard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(surfboard);
        }
        #endregion

        #region Edit
        // GET: Surfboards/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Surfboard == null)
            {
                return NotFound();
            }

            var surfboard = await _context.Surfboard.FindAsync(id);
            if (surfboard == null)
            {
                return NotFound();
            }
            return View(surfboard);
        }

        #region Out-commented
        // POST: Surfboards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit(int? id, byte[] rowVersion)
        //{
        //    string fieldsToBind = "Id,Name,Length,Width,Thickness,Volume,Type,Price,Equipment,ImgUrl,RowVersion";

        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var departmentToUpdate = await _context.Surfboard.FindAsync(id);
        //    if (departmentToUpdate == null)
        //    {
        //        Surfboard deletedDepartment = new Surfboard();
        //        TryUpdateModelAsync(deletedDepartment, fieldsToBind);
        //        ModelState.AddModelError(string.Empty,
        //            "Unable to save changes. The department was deleted by another user.");
        //        return View(deletedDepartment);
        //    }

        //    if (await TryUpdateModelAsync(departmentToUpdate, fieldsToBind))
        //    {
        //        try
        //        {
        //            _context.Surfboard.Entry(departmentToUpdate).OriginalValues["RowVersion"] = rowVersion;
        //            _context.Update(departmentToUpdate);
        //            await _context.SaveChangesAsync();

        //            return RedirectToAction("Index");
        //        }
        //        catch (DbUpdateConcurrencyException ex)
        //        {
        //            var entry = ex.Entries.Single();
        //            var clientValues = (Surfboard)entry.Entity;
        //            var databaseEntry = entry.GetDatabaseValues();
        //            if (databaseEntry == null)
        //            {
        //                ModelState.AddModelError(string.Empty,
        //                    "Unable to save changes. The department was deleted by another user.");
        //            }
        //            else
        //            {
        //                var databaseValues = (Surfboard)databaseEntry.ToObject();

        //                if (databaseValues.Id != clientValues.Id)
        //                    ModelState.AddModelError("Id", "Current value: "
        //                        + databaseValues.Id);

        //                if (databaseValues.Name != clientValues.Name)
        //                    ModelState.AddModelError("Name", "Current value: "
        //                        + databaseValues.Name);

        //                if (databaseValues.Length != clientValues.Length)
        //                    ModelState.AddModelError("Lenght", "Current value: "
        //                        + databaseValues.Length);

        //                if (databaseValues.Width != clientValues.Width)
        //                    ModelState.AddModelError("Width", "Current value: "
        //                        + databaseValues.Width);

        //                if (databaseValues.Thickness != clientValues.Thickness)
        //                    ModelState.AddModelError("Thickness", "Current value: "
        //                        + databaseValues.Thickness);

        //                if (databaseValues.Volume != clientValues.Volume)
        //                    ModelState.AddModelError("Volume", "Current value: "
        //                        + databaseValues.Volume);

        //                if (databaseValues.Type != clientValues.Type)
        //                    ModelState.AddModelError("Type", "Current value: "
        //                        + databaseValues.Type);

        //                if (databaseValues.Price != clientValues.Price)
        //                    ModelState.AddModelError("Price", "Current value: "
        //                        + databaseValues.Price);

        //                if (databaseValues.ImgUrl != clientValues.ImgUrl)
        //                    ModelState.AddModelError("ImgUrl", "Current value: "
        //                        + databaseValues.ImgUrl);

        //                if (databaseValues.RowVersion != clientValues.RowVersion)
        //                    ModelState.AddModelError("RowVersion", "Current value: "
        //                        + databaseValues.RowVersion);

        //                ModelState.AddModelError(string.Empty, "The record you attempted to edit "
        //                    + "was modified by another user after you got the original value. The "
        //                    + "edit operation was canceled and the current values in the database "
        //                    + "have been displayed. If you still want to edit this record, click "
        //                    + "the Save button again. Otherwise click the Back to List hyperlink.");
        //                departmentToUpdate.RowVersion = databaseValues.RowVersion;
        //            }
        //        }
        //        catch (RetryLimitExceededException /* dex */)
        //        {
        //            //Log the error (uncomment dex variable name and add a line here to write a log.)
        //            ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
        //        }
        //    }
        //    return View(departmentToUpdate);
        //}
        #endregion

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, byte[] rowVersion)
        {
            //string fieldsToBind = "Id,Name,Length,Width,Thickness,Volume,Type,Price,Equipment,ImgUrl,RowVersion";

RentalWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | App </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc_surfboard.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a 
                    class="navbar-brand" 
                    asp-area="" 
                    asp-controller="Home" 
                    asp-action="Index"
                >
                    <img src="https://cdn-icons-png.flaticon.com/512/4363/4363838.png"
                         class="app-logo" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a 
                                class="nav-link text-dark" 
                                asp-area="" 
                                asp-controller="Surfboards" 
                                asp-action="Index"
                            >
                                Udlejning
                            </a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 | App- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>